In [1]:
import tensorflow as tf

/home/ryoji/Documents/git/practice/python_ML/ゼロからDL自然言語/nlp/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/ryoji/Documents/git/practice/python_ML/ゼロからDL自然言語/nlp/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/ryoji/Documents/git/practice/python_ML/ゼロからDL自然言語/nlp/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtyp

In [39]:
import sys
sys.path.append('../common')

In [94]:
A = tf.constant([1, 2, 3,4,5,6], shape=(2,3), dtype='double')
B = tf.constant([2,2,3,4,4,6], shape=(2,3))

In [95]:
A

<tf.Tensor: id=378, shape=(2, 3), dtype=float64, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]])>

In [92]:
tf.matmul(A, tf.transpose(B))

<tf.Tensor: id=374, shape=(2, 2), dtype=int32, numpy=
array([[15, 30],
       [36, 72]], dtype=int32)>

In [27]:
X = tf.random.uniform((10, 2))
W1 = tf.random.uniform((2,4))
b1 = tf.random.uniform((4,))

In [33]:
h = tf.matmul(X, W1) + b1

In [36]:
def sigmoid(x):
    return 1 / (1 + tf.math.exp(-x))

In [37]:
sigmoid(X)

<tf.Tensor: id=117, shape=(10, 2), dtype=float32, numpy=
array([[0.6637893 , 0.6121439 ],
       [0.5383068 , 0.6454277 ],
       [0.65633607, 0.63247687],
       [0.7014841 , 0.71654576],
       [0.5092323 , 0.5227617 ],
       [0.5559879 , 0.70846534],
       [0.6375815 , 0.63985896],
       [0.59197605, 0.5701761 ],
       [0.71352273, 0.72591376],
       [0.6008159 , 0.5600434 ]], dtype=float32)>

In [90]:
tf.range(10)[1:3]

<tf.Tensor: id=364, shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [88]:
tf.random.shuffle(tf.range(10))

<tf.Tensor: id=350, shape=(10,), dtype=int32, numpy=array([2, 5, 9, 3, 8, 0, 7, 6, 4, 1], dtype=int32)>

In [58]:
class SGD:
    def __init__(self, lr=0.01):
        self.lr = lr
        
    def updata(self, params, grads):
        for i in range(len(params)):
            params[i] -= self.lr* grads[i]

In [57]:
class Sigmoid:
    def __init__(self):
        self.params = []
        
    def forward(self, x):
        self.out = 1 / (1 + tf.math.exp(-x))
        return self.out
    
    def backward(self, dout):
        dx = dout * (1.0 - self.out) * self.out
        return dx
    
class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
    
    def forward(self, x):
        W, b = self.params
        out = tf.matmul(x, W) + b
        return out
    
    def backward(self, dout):
        W, b = self.params
        dx = tf.matmul(dout, tf.transpose(W))
        dW = tf.matmul(tf.transpose(self.x), dout)
        db = tf.math.reduce_sum(dout, axis=0)
        
        self.grads[0][...] = dW
        self.grads[1][...] = db
        return dx
    
class MatMul:
    def __init__(self, W):
        self.params = W
        self.grads = [tf.zeros_like(W)]
        self.x = None
        
    def forward(self, x):
        W, = self.params
        self.x = x
        out = tf.matmul(x, W)
        return out
    
    def backward(self, dout):
        W, = self.params
        dx = tf.matmul(dout, tf.transpose(W))
        dW = tf.matmul(tf.transpose(self.x), dout)
        self.grads[0][...] = dW
        return dx
    

In [45]:
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size
        
        W1 = tf.random.uniform((I, H))
        b1 = tf.random.uniform((H, ))
        W2 = tf.random.uniform((H, O))
        b2 = tf.random.uniform((O, ))
        
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]
        
        self.params = []
        for layer in self.layers:
            self.params += layer.params
            
    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x
    

In [48]:
x = tf.random.uniform((10, 2))
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)
s

<tf.Tensor: id=251, shape=(10, 3), dtype=float32, numpy=
array([[1.6644661, 1.930121 , 2.7181914],
       [1.6465619, 1.904007 , 2.673863 ],
       [1.7184678, 2.0019763, 2.8370163],
       [1.6523311, 1.9039899, 2.6685228],
       [1.6993067, 1.9835781, 2.8114474],
       [1.662851 , 1.9397384, 2.7422428],
       [1.6561893, 1.9327073, 2.7319694],
       [1.6199859, 1.8839008, 2.6517048],
       [1.6630063, 1.9126091, 2.6787553],
       [1.6555686, 1.9185008, 2.6992974]], dtype=float32)>

In [56]:
tf.math.reduce_sum(x, axis=1, keepdims=False)

<tf.Tensor: id=264, shape=(10,), dtype=float32, numpy=
array([0.93025637, 0.7877674 , 1.4972013 , 0.8771541 , 1.2274141 ,
       0.84963393, 0.78243744, 0.5015609 , 1.0022548 , 0.8507818 ],
      dtype=float32)>